### ISSUE TITLE
Adyen binding for iOS

### ISSUE THREAD

**Issue by siuhleung7** [NAXAM/adyen-android-binding#1]
Hi @tuyen-vuduc 

Thank you for providing this great repository for Xamarin.Android.
However, I am now getting a trouble when I doing on Xamarin.iOS. Adyen only provides the swift framework that hard to bind into Xamarin.iOS...

So, would you share the binding or a tutorial for Xamarin.iOS also??

Thank you very much!

**Comment by tuyen-vuduc** [comment]
The binding guideline could be found [here](https://medium.com/@Flash3001/binding-swift-libraries-xamarin-ios-ff32adbc7c76)

**Comment by siuhleung7** [comment]
Thanks for your reply @tuyen-vuduc 

I have tried to follow the guideline, but still unable to work.
Once I just the swift binding then the apps will start and then close.

And based on this example
https://github.com/Adyen/adyen-ios/tree/master/Examples/Objective-C%20Example

[ApiDefinition.zip](https://github.com/Flash3001/Xamarin.BindingSwiftLibrarySample/files/2135924/ApiDefinition.zip)
[Adyen_ios_binding.framework.zip](https://github.com/Flash3001/Xamarin.BindingSwiftLibrarySample/files/2135916/Adyen_ios_binding.framework.zip)

Would you consider to provide the adyen-ios-binding like Stripe?

Thanks again.

**Comment by tuyen-vuduc** [comment]
Plz check adyen-ios binding on Nuget.
